Module2 task2
htmlacademy-adaptive/1359579-mishka-23 pull request #3
Opened 2021-07-28 08:45 UTC by alenushka-jpg

2021-07-28 23:20 UTC, wrgraff requested changes

2021-07-28 23:20 UTC, wrgraff commented on source/catalog.html
> +        <div class="intro__container container">
И тут обертка... Ох

2021-07-28 23:20 UTC, wrgraff commented on source/catalog.html
> +            <li class="card-product__item">
Я крайне рекомендую сделать общую секцию одним блоком, а сами карточки каталога, каждую — своим отдельным блоком.
Иначе получается слишком сложный один блок

2021-07-28 23:20 UTC, wrgraff commented on source/catalog.html
> +      <section class="card-product">
Секции нужен свой отдельный заголовок

2021-07-28 23:20 UTC, wrgraff commented on source/catalog.html
> +                <span class="visually-hidden">Добавить в корзину зайчика-попрыгайчика</span>
На практике сгенерировать такие тексты будет очень сложно, обычно пишут "Добавить в корзину"

2021-07-28 23:20 UTC, wrgraff commented on source/catalog.html
> +              <a class="card-product__link" href="#">
Раз там есть `card-product__title-link`, то хочется добавить здесь по аналогии `card-product__img-link`

2021-07-28 23:20 UTC, wrgraff commented on source/form.html
> +              </li>
Вроде как можно активные страницы отметить (хотя они не стилизованы никак кажется)

2021-07-28 23:20 UTC, wrgraff commented on source/form.html
> +          </p>
Кажется, этот текст идет после интро все-таки.
Будет сложновато его оформить так, чтобы волна шла под заголовком, но до текста.

2021-07-28 23:20 UTC, wrgraff commented on source/form.html
> +          </fieldset>
Как-то хорошо размечено. Ты сразу так сделала или по моему видео с разметкой формы ориентировалась?

2021-07-28 23:20 UTC, wrgraff commented on source/form.html
> +                    <span class="visually-hidden">Введите ваше имя*</span>
Так, внутри инпута ничего не бывает )

2021-07-28 23:20 UTC, wrgraff commented on source/form.html
> +              <input class="contacts__input" type="text" name="phone" placeholder="+7 ХХХ ХХХ ХХ ХХ*">
Можно указать тип, соответствующий номеру телефона
```suggestion
              <input class="contacts__input" type="tel" name="phone" placeholder="+7 ХХХ ХХХ ХХ ХХ*">
```

2021-07-28 23:20 UTC, wrgraff commented on source/form.html
> +              <input class="contacts__input" type="text" name="email" placeholder="Ваш Email*">
А тут создать тип для поля почты
```suggestion
              <input class="contacts__input" type="email" name="email" placeholder="Ваш Email*">
```

2021-07-28 23:20 UTC, wrgraff commented on source/form.html
> +              </textarea>
Имей ввиду, что форматирование в разметке перенесется в содержимое textarea

2021-07-28 23:20 UTC, wrgraff commented on source/form.html
> +          <fieldset class="user-data__fieldset user-data__fieldset--message">
Тут есть сомнения на тему группы полей из одного поля.
С другой стороны — единообразие.

Так что сама думай )

2021-07-28 23:20 UTC, wrgraff commented on source/form.html
> +            <button class="user-data__button button" type="submit">отправить заказ</button>
Все-таки  писать принято с большой буквы

2021-07-29 05:38 UTC, alenushka-jpg commented on source/form.html
> +          </fieldset>
На твое видео ориентировалась

2021-07-29 16:51 UTC, wrgraff commented on source/form.html
> +          </fieldset>
Хитрюшка

2021-07-29 17:09 UTC, wrgraff requested changes
С контейнерами я не совсем это имел ввиду.
Не обязательно было все их миксовать на уровень выше, речь то шла только про h1 внутри intro...
Но ладно, сетки начнем — выведем обертки тогда уже.

2021-07-29 17:09 UTC, wrgraff commented on source/catalog.html
> +        <h1 class="intro__title">Каталог товаров</h1>
Я имел ввиду на заголовок:
```suggestion
      <section class="intro">
        <h1 class="intro__title container">Каталог товаров</h1>
```

Контейнер же должен быть внутри блока. На самом блоке он может быть только если у него фон не тянется (Но вполне допустимо для единообразия сделать контейнеры всегда внутри)

2021-07-29 17:09 UTC, wrgraff commented on source/catalog.html
> +        <h2 class="visually-hidden">Карточки товаров</h2>
Лучше "список товаров" назвать, наверное.
Но это так, ерунда

2021-07-29 17:09 UTC, wrgraff commented on source/form.html
> +                </input>
Я же говорю, наоборот, в инпуте не может быть никаких тегов.
Это одиночный тег. В него нельзя ничего вложить.
Ты почему-то вместо того, чтобы убрать эту ошибку в одном месте, добавила еще и в другом...

2021-07-29 17:09 UTC, wrgraff commented on source/form.html
> +                </input>
Разметка была нормальная же

2021-07-29 17:41 UTC, wrgraff approved these changes

2021-07-29 17:41 UTC, merged